services:
  db:
    image: postgres:12-alpine
    container_name: mini_proyecto
    restart: always
    environment:
      - POSTGRES_USER=pereiradm
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mini_proyecto
    ports:
      - "5451:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
